### ISSUE TITLE
Change status action was not fired

### ISSUE THREAD

**Issue by duyanhth** [LiamMcArthur/woocommerce-autocomplete-orders#5]
Hi LiamMcAuthur

When changing Order Status to 'Completed' please also fire correct action such as 'woocommerce_order_status_processing_to_completed'
Currently there is no action was fired

Regards
Tran

**Comment by LiamMcArthur** [comment]
I'm not quite sure I understand. The autocomplete orders plugin automatically changes the order to status to completed (WooCommerce then automatically runs `woocommerce_order_status_completed`).

**Comment by duyanhth** [comment]
Hello dear,

thank you very much and I'm sorry for taking your time. 
Yes, you are right about it. E.g. nothing wrong with your great plugin
I'm new to woocommerce so I made wrong report. 
Original issue was woocommerce_payment_complete event was not fired (because actually payment is not completed yet) but I expected the payment is done when Order Status is Completed :(

Regards
Tran
